### ISSUE TITLE
evaluating with COCOeval very slow

### ISSUE THREAD

**Issue by XiaoyuWant** [tyomj/product_detection#6]
Hello, I finished training and generated the result JSON file. But when evaluating with COCOeval on JSON file and test JSON, the calculation is prolonged, maybe one hour. I want to ask whether you have occurred this problem.

**Comment by tyomj** [comment]
Hi, 
COCOeval from pycocotools might be really slow due to mAP50:95 calculation, which is why in [some repositories](https://github.com/ultralytics/yolov5/issues/2258) an alternative calculation method is used. but as far as I remember, it took me less than an hour for the test part of the SKU110k dataset.
